### ISSUE TITLE
由于selenium版本更新导致的无法运行

### ISSUE THREAD

**Issue by GrandDuke1106** [tyIceStream/zodgame_checkin#27]
```
Run python3 ./zodgame/zodgame.py "***"
Traceback (most recent call last):
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 184, in <module>
    zodgame(cookie_string)
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 144, in zodgame
    driver = uc.Chrome(version_main=version, options = options)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\undetected_chromedriver\__init__.py", line 453, in __init__
    super(Chrome, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'executable_path'
Error: Process completed with exit code 1.
```

临时的解决方法是在``requirements.txt``文件中，第一行添加``selenium==4.9.1``

```
selenium==4.9.1
undetected-chromedriver
```

如果大佬有空可以针对新版本修一下

**Comment by tyIceStream** [comment]
undetected-chromedriver已经修复此问题，感谢您提供的方案。
