### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by szsc233** [tyIceStream/zodgame_checkin#31]
这样

Run python3 ./zodgame/zodgame.py "***"
Traceback (most recent call last):
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 1[8](https://github.com/szsc233/zodgame_checkin/actions/runs/5978310098/job/16220124308#step:4:9)8, in <module>
    zodgame(cookie_string)
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 148, in zodgame
    driver = uc.Chrome(options = options)
  File "C:\hostedtoolcache\windows\Python\3.[9](https://github.com/szsc233/zodgame_checkin/actions/runs/5978310098/job/16220124308#step:4:10).13\x64\lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60412
from session not created: This version of ChromeDriver only supports Chrome version 116
Current browser version is 115.0.5790.171
Stacktrace:
	GetHandleVerifier [0x002D37C3+48947]
	(No symbol) [0x00268551]
	(No symbol) [0x0016C92D]
	(No symbol) [0x0018F180]
	(No symbol) [0x001895E1]
	(No symbol) [0x00189447]
	(No symbol) [0x001BB840]
	(No symbol) [0x001BB3CC]
	(No symbol) [0x001B4E86]
	(No symbol) [0x001916C7]
	(No symbol) [0x0019284D]
	GetHandleVerifier [0x0051FDF9+2458985]
	GetHandleVerifier [0x0056744F+2751423]
	GetHandleVerifier [0x00561361+2726609]
	GetHandleVerifier [0x00350680+560624]
	(No symbol) [0x0027238C]
	(No symbol) [0x0026E268]
	(No symbol) [0x0026E392]
	(No symbol) [0x0026[10](https://github.com/szsc233/zodgame_checkin/actions/runs/5978310098/job/16220124308#step:4:11)B7]
	BaseThreadInitThunk [0x76D66A39+25]
	RtlGetFullPathName_UEx [0x77AF7E4D+173]
	RtlGetFullPathName_UEx [0x77AF7E1B+[12](https://github.com/szsc233/zodgame_checkin/actions/runs/5978310098/job/16220124308#step:4:13)3]
	(No symbol) [0x00000000]

**Comment by tyIceStream** [comment]
感谢提醒，已经修复了，请同步一下吧。

**Comment by szsc233** [comment]
可以了，感谢修复
